use anyhow::Result;
use std::{fs, path::Path};
use dialoguer::Select;

pub fn run (name: String) -> Result<()> {
    println!("🚀 Creating project: {}", name);

    let stack: Vec<&str> = vec![".Net SPA", "MEAN", "MERN", "Vue-Laravel"];
    println!("📚 Available stacks:");
    for s in &stack {
        println!(" - {}", s);
    }

    let selection: usize = Select::new()
        .with_prompt("Select a stack")
        .items(&stack)
        .default(0)
        .interact()?;

    let selected_stack: &str = stack[selection];

    println!("📦 Stack selected: {}", selected_stack);
    create_project_structure(&name)?;
    println!("✅ Project created successfully!");
    Ok(())
}


fn create_project_structure(name: &str) -> Result<()> {
    let root = Path::new(name);

    if root.exists() {
        anyhow::bail!("folder already exists");
    }

    fs::create_dir(root)?;
    fs::create_dir(root.join("frontend"))?;
    fs::create_dir(root.join("backend"))?;
    fs::write(root.join("README.md"), 
    format!("# {}\n\nGenerated by LilPinpong CLI 🚀", name))?;

    Ok(())
}
