use anyhow::Result;
use std::{fs, path::Path, process::Command};
use dialoguer::Select;

pub fn run (name: String) -> Result<()> {
    println!("🚀 Creating project: {}", name);

    let stack: Vec<&str> = vec![".Net SPA", "MEAN", "MERN", "Vue-Laravel"];

    let selection: usize = Select::new()
        .with_prompt("📚 Select stack for your project:")
        .items(&stack)
        .default(0)
        .interact()?;

    let selected_stack: &str = stack[selection];

    println!("📦 Stack selected: {}", selected_stack);
    create_project_structure(&name, selected_stack)?;
    println!("✅ Project created successfully!");
    Ok(())
}


fn create_project_structure(name: &str, selected_stack: &str) -> Result<()> {
    let root = Path::new(name);

    if root.exists() {
        anyhow::bail!("folder already exists");
    }


    fs::create_dir(root)?;
    fs::create_dir(root.join("project"))?;
    fs::create_dir(root.join("server"))?;

   match selected_stack {
        ".Net SPA" => {
            println!("☣️ Setting up .Net SPA structure... ☣️");
        },
        "MEAN" => {
            println!("☣️ Setting up MEAN stack structure... ☣️");
            Command::new("cd project").output()?;
            let clit_output = Command::new("npm")
                .arg("install")
                .arg("-g")
                .arg("@angular/cli")
                .output()?;
                if !clit_output.status.success() {
                    anyhow::bail!("Failed to install Angular CLI: {}", String::from_utf8_lossy(&clit_output.stderr));
                }
            let angular_output = Command::new("ng")
                .arg("new") 
                .arg(name)
                .output()?;
                if !angular_output.status.success() {
                    anyhow::bail!("Failed to create Angular project: {}", String::from_utf8_lossy(&angular_output.stderr));
                }

            Command::new("cd ..").output()?;
            Command::new("cd server").output()?;
            let express_output = Command::new("npm")
                .arg("install")
                .arg("express")
                .output()?;
                if !express_output.status.success() {
                    anyhow::bail!("Failed to install Express: {}", String::from_utf8_lossy(&express_output.stderr));
                }

            if(express_output.status.success() && angular_output.status.success()) {
                println!("✅ MEAN stack structure created successfully! ✅");
            }
        },
        "MERN" => {
            println!("☣️ Setting up MERN stack structure... ☣️");
            // Here you would add code to create the specific structure for MERN stack
        },
        "Vue-Laravel" => {
            println!("☣️ Setting up Vue-Laravel structure... ☣️");
            // Here you would add code to create the specific structure for Vue-Laravel stack
        },
        _ => {
            anyhow::bail!(" ❌ Invalid stack selection ❌");
        }
    }

    fs::write(root.join("README.md"), 
    format!("# {}\n\nGenerated by LilPinpong CLI 🚀", name))?;

    Ok(())
}
